# Generated by Django 4.0.3 on 2022-06-01 17:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Black_List_Models',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('data_domain', models.CharField(blank=True, default='', max_length=999)),
                ('note', models.CharField(blank=True, default='', max_length=999)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(blank=True, default='', max_length=255)),
                ('add_dns', models.TextField(blank=True, default='')),
                ('delete_dns', models.TextField(blank=True, default='')),
                ('not_add_dns_filter', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='DNS_filter_Models',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('data_domain', models.CharField(blank=True, default='', max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('add_dns', models.TextField(blank=True, default='')),
                ('count', models.CharField(blank=True, default='', max_length=225)),
                ('delete_dns', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Dns_Node_Models',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(blank=True, default='', max_length=255)),
                ('ip_address', models.CharField(blank=True, default='', max_length=255)),
                ('mac_address', models.CharField(blank=True, default='', max_length=255)),
                ('os', models.CharField(blank=True, default='', max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('is_raw_black_list', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DnsRecordsModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domian', models.CharField(blank=True, default='', max_length=255)),
                ('ip', models.CharField(blank=True, default='', max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('add_dns', models.TextField(blank=True, default='')),
                ('delete_dns', models.TextField(blank=True, default='')),
                ('not_add_dns_filter', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='White_List_Models',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('data_domain', models.CharField(blank=True, default='', max_length=225)),
                ('note', models.CharField(blank=True, default='', max_length=225)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(blank=True, default='', max_length=255)),
                ('add_dns', models.TextField(blank=True, default='')),
                ('delete_dns', models.TextField(blank=True, default='')),
                ('not_add_dns_filter', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Monitor_DNS_Models',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ram', models.CharField(blank=True, default='', max_length=100)),
                ('cpu', models.CharField(blank=True, default='', max_length=100)),
                ('disk', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(blank=True, default='', max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('dns_center_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_part.dns_node_models')),
            ],
        ),
        migrations.CreateModel(
            name='Log_Detail_Models',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_client', models.CharField(blank=True, default='', max_length=255)),
                ('domain', models.CharField(blank=True, default='', max_length=255)),
                ('access_time', models.DateTimeField(blank=True, default='')),
                ('status', models.CharField(blank=True, default='', max_length=255)),
                ('dns_center_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_part.dns_node_models')),
            ],
        ),
    ]
