# Generated by Django 4.0.3 on 2022-06-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_part', '0002_dns_node_models_is_raw_regex_black_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dns_node_models',
            name='is_dns_dnsrecord',
            field=models.BooleanField(default=False),
        ),
    ]
