# Generated by Django 4.0.3 on 2022-06-07 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_part', '0003_dns_node_models_is_dns_dnsrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='black_list_models',
            name='delete_dns',
        ),
        migrations.RemoveField(
            model_name='black_list_models',
            name='not_add_dns_filter',
        ),
        migrations.RemoveField(
            model_name='dnsrecordsmodel',
            name='delete_dns',
        ),
        migrations.RemoveField(
            model_name='dnsrecordsmodel',
            name='not_add_dns_filter',
        ),
        migrations.RemoveField(
            model_name='white_list_models',
            name='delete_dns',
        ),
        migrations.RemoveField(
            model_name='white_list_models',
            name='not_add_dns_filter',
        ),
    ]
