# Generated by Django 4.0.3 on 2022-06-14 10:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main_part', '0004_remove_black_list_models_delete_dns_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DnsForwarderModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('add_dns', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AddField(
            model_name='dns_node_models',
            name='is_dns_forwarder',
            field=models.BooleanField(default=False),
        ),
    ]
