# Generated by Django 4.0.3 on 2022-06-20 01:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main_part', '0005_dnsforwardermodel_dns_node_models_is_dns_forwarder'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogToFileModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log_line', models.TextField(blank=True, default='')),
                ('dns_center_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_part.dns_node_models')),
            ],
        ),
    ]
