# Generated by Django 4.0.3 on 2022-06-30 00:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main_part', '0006_logtofilemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharBlackWhiteList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_time', models.CharField(blank=True, default='', max_length=255)),
                ('count_black', models.CharField(blank=True, default='', max_length=255)),
                ('count_white', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
