# Generated by Django 4.0.3 on 2022-08-03 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_part', '0007_charblackwhitelist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CharBlackWhiteList',
        ),
    ]
