# Generated by Django 4.0.3 on 2022-08-03 10:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main_part', '0008_delete_charblackwhitelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpSiemToWeb',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_siem', models.CharField(blank=True, default='', max_length=255)),
                ('port_siem', models.CharField(blank=True, default='', max_length=255)),
                ('is_connect', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
