# Generated by Django 4.0.3 on 2022-05-17 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_admin_customuser_is_super_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_super',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_user',
        ),
    ]
